# https://taskfile.dev

version: '2'

vars:
  GREETING: Hello, World!

tasks:
  update:
    cmds:
      - go mod tidy -v
      - go mod vendor -v

  build:
    cmds:
      - go build -mod=vendor -ldflags="-s -w"

  run:
    deps: [build]
    cmds:
      - ./goStudy

  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
